---
title: "Results per metrics"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---



```{r}
library(knitr)
## Loading the results
load("../Data/Processed/sim_equalizing.rda")
equalizing <- bkp
load("../Data/Processed/sim_facilitation.rda")
facilitation <- bkp
load("../Data/Processed/sim_filtering.rda")
filtering <- bkp
load("../Data/Processed/sim_competition.rda")
competition <- bkp
```

```{r}
## Loading the functions
source("../Functions/extract.table.R")
source("../Functions/plot.metric.results.R")
source("../Functions/paired.tests.R")
source("../Functions/split.metric.R")
source("../Functions/fit.model.rm.R")
source("../Functions/fancy.table.R")
source("../Functions/fancy.plot.R")
```

# Results per metrics

```{r}
## Creating the list of results
all_results <- list(equalizing   = equalizing,
                    facilitation = facilitation,
                    filtering    = filtering,
                    competition  = competition)
## The different removal level names
removals <- c("20%", "40%", "60%", "80%")
## The colours
cols <- c("blue", "orange", "red", "green")
```

# Plots per metric

## Tree metrics

### Alpha

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "tree_alpha", scale.method = "between", level.names = removals, col = cols)
```

### Dispersion

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "tree_dispersion", scale.method = "between", level.names = removals, col = cols)
```

### Evenness

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "tree_evenness", scale.method = "between", level.names = removals, col = cols, legend.pos = "bottomright")
```

## Dissimilarity metrics 

### Rao

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "FD_Rao", scale.method = "between", level.names = removals, col = cols, legend.pos = "bottomright")
```

### Divergence (FD)

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "FD_divergence", scale.method = "between", level.names = removals, col = cols, legend.pos = "bottomright")
```

### Evenness (FD)

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "FD_evenness", scale.method = "between", level.names = removals, col = cols, legend.pos = "bottomright")
```

### Melodic Rao

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "melodic_Rao", scale.method = "between", level.names = removals, col = cols)
```

### Melodic MPD

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "melodic_mpd", scale.method = "between", level.names = removals, col = cols)
```         

## Convex hull metrics

### Convex hull alpha

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "convex.hull", scale.method = "between", level.names = removals, col = cols)
```  

## Hypervolume metrics

### Richness

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "hypervolume_richness", scale.method = "between", level.names = removals, col = cols)
``` 

### Dispersion

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "hypervolume_dispersion", scale.method = "between", level.names = removals, col = cols)
``` 

### Regularity

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "hypervolume_regularity", scale.method = "between", level.names = removals, col = cols)
``` 

## Probability density metrics

### Richness

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "TPD_Richness", scale.method = "between", level.names = removals, col = cols)
``` 

### Evenness

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "TPD_Evenness", scale.method = "between", level.names = removals, col = cols)
``` 

### Divergence

```{r, fig.height = 4, fig.width = 12, eval = TRUE, echo = FALSE}
plot.metric.results(all_results, metric = "TPD_Divergence", scale.method = "between", level.names = removals, col = cols)
``` 

```{r, eval = FALSE, message = FALSE, fig.width = 12, fig.height = 12, echo = FALSE}
```
